// Import the necessary modules from AWS Amplify
import { Auth } from "aws-amplify";

// Configure AWS Amplify
import awsconfig from "./aws-exports"; // Ensure this file is correctly generated by Amplify
Auth.configure(awsconfig);

// Function to handle user signup
async function signUp(event) {
  event.preventDefault(); // Prevent default form submission

  const email = document.getElementById("email").value; // Get email from input field
  const password = document.getElementById("password").value; // Get password from input field

  try {
    const { user } = await Auth.signUp({
      username: email, // Use email as the username (Cognito requires a unique username)
      password,
      attributes: { email }, // Specify email attribute
    });
    console.log(user); // Log user details for debugging
    alert("Signup successful! Please check your email for verification.");
  } catch (error) {
    console.error(error);
    alert("Error signing up: " + error.message);
  }
}

// Event listener for the signup form submission
document.getElementById("signupButton").addEventListener("click", signUp);
